modLoader = "javafml"
loaderVersion = "[36,)"
license = "$GPL-2.0 license"
[[mods]]
modId = "tridot"
version = "${file.jarVersion}"
displayName = "Tridot"
authors = "IriDark, Auriny, Skoow"

description = '''API mod for Komaru org'''
[[dependencies.tridot]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.tridot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
